spring:
  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 0 #????0????
    jedis:
      #Redis?????
      pool:
        max-active: 8 #?????
        max-wait: 1ms #???????????
        max-idle: 4 #???????????
        min-idle: 0 #???????????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/waimou?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  application:
    name: consumer
server:
  port: 9000
